name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE.txt'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE.txt'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        run: |
          rustup update --no-self-update stable

      - name: Build and Test
        run: |
          RUST_BACKTRACE=short cargo test -- --quiet
